services:
  - type: web
    name: rentfreely
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec jekyll build
    staticPublishPath: _site
    pullRequestPreviewsEnabled: false
    envVars:
      - key: JEKYLL_ENV
        value: production
